### ISSUE TITLE
What wasm file?

### ISSUE THREAD

**Issue by justinmchase** [ayame113/ts-serve#25]
> Optionally, calling the fourceInstantiateWasm function before starting the server will force the wasm file to be read ahead. Otherwise the wasm file will take about 3 seconds to load the first time it is transpiled.

It seems like the documentation in this area could be a little clearer about what wasm file is being instantiated and why its needed at all.

**Comment by ayame113** [comment]
Thanks for your feedback! This is about the wasm file included in deno_emit. I agree that the documentation should be more detailed.
