### ISSUE TITLE
compile TypeScript folder in advance

### ISSUE THREAD

**Issue by jiawei397** [ayame113/ts-serve#32]
Is there any way to compile the target TypeScript folder in advance?

In addition, it would be better if you could control whether to generate sourcemap.

**Comment by ayame113** [comment]
> Is there any way to compile the target TypeScript folder in advance?

Lume, a static site generator, is probably the best choice for this purpose! [The esbuild plugin](https://lume.land/plugins/esbuild/) allows you to compile any typescript you have in a folder in advance.

> In addition, it would be better if you could control whether to generate sourcemap.

I'd like to do this, but first I need to resolve https://github.com/denoland/deno_emit/issues/29, an upstream issue.
(please see also https://github.com/denoland/deno_emit/issues/83.)

**Comment by jiawei397** [comment]
As for the first point, I mean how to pre-cache when using your tool library. If I use it in production, It is better precompile the ts file first. Because I found that one of my ts files, although not large, took 1 second for the first time, which may be a serious problem in production.

**Comment by ayame113** [comment]
> Because I found that one of my ts files, although not large, took 1 second for the first time

In that case, it may be taking a long time to read the wasm file. Why not try [fourceInstantiateWasm](https://deno.land/x/ts_serve@v1.4.4/mod.ts?s=fourceInstantiateWasm) function? (Sorry if you've already tried it.)

**Comment by jiawei397** [comment]
Very good. This may be what I need.
