### ISSUE TITLE
Update deno.land to v1.4.5  (currently 1.4.4 is latest)

### ISSUE THREAD

**Issue by lukakostic** [ayame113/ts-serve#39]
As title says. In releases here you have v1.4.5 but on deno.land its only 1.4.4
(I assume you- the author uploads versions there). But its a small thing.

Anyways thank you so much @ayame113 for this wonderful little project.
It makes it very easy to save as a script and run anytime you want (like `python3 -m http.server`)
 to do quick web dev and seamlessly use `.ts` instead of `.js` without waiting for compilation and setting everything up.

**Comment by ayame113** [comment]
Hello! Thank you for your interest in this module.

I apologize for not having 1.4.5 released.

I've just released [v1.5 to jsr.io](https://jsr.io/@ayame113/ts-serve)! Please give it a try!
